import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const categories = [
  {
    id: 1,
    name: "Carrefour",
    name_ar: "كارفور",
    facebook_link: "https://www.facebook.com/CarrefourMa",
    instagram_link: "https://www.instagram.com/carrefour.maroc",
    tiktok_link: "https://www.tiktok.com/@carrefourmaroc",
  },
  {
    id: 2,
    name: "Carrefour Market",
    name_ar: "كارفور ماركت",
    facebook_link: "https://www.facebook.com/CarrefourMarketMaroc",
    instagram_link: "https://www.instagram.com/carrefourmarket.maroc",
    tiktok_link: null,
  },
  {
    id: 3,
    name: "Carrefour Gourmet",
    name_ar: "كارفور جورميه",
    facebook_link: "https://www.facebook.com/Carrefourgourmetmaroc",
    instagram_link: "https://www.instagram.com/carrefourmarketgourmet",
    tiktok_link: null,
  },
  {
    id: 4,
    name: "Carrefour Express",
    name_ar: "كارفور إكسبرس",
    facebook_link: "https://www.facebook.com/CarrefourExpressMaroc",
    instagram_link: "https://www.instagram.com/carrefourexpressmaroc",
    tiktok_link: null,
  },
];

const cities = [
  {
    id: 1,
    name: "Rabat",
  },
  {
    id: 2,
    name: "Meknès",
  },
  {
    id: 3,
    name: "Marrakech",
  },
  {
    id: 4,
    name: "Casablanca",
  },
  {
    id: 5,
    name: "Marrakesh",
  },
  {
    id: 6,
    name: "Fès",
  },
  {
    id: 7,
    name: "Meknes",
  },
  {
    id: 8,
    name: "Tanger",
  },
  {
    id: 9,
    name: "Agadir",
  },
  {
    id: 10,
    name: "El Jadida",
  },
  {
    id: 11,
    name: "Tamaris",
  },
  {
    id: 12,
    name: "Essaouira",
  },
  {
    id: 13,
    name: "Temara",
  },
  {
    id: 14,
    name: "Dar-el-Beida",
  },
  {
    id: 15,
    name: "Kénitra",
  },
  {
    id: 16,
    name: "Mohammedia",
  },
  {
    id: 17,
    name: "Khémisset",
  },
  {
    id: 18,
    name: "Tétouan",
  },
  {
    id: 19,
    name: "Ouarzazate",
  },
  {
    id: 20,
    name: "BenHimaSafi",
  },
  {
    id: 21,
    name: "Salé",
  },
  {
    id: 22,
    name: "Settat",
  },
  {
    id: 23,
    name: "Béni Mellal",
  },
  {
    id: 24,
    name: "Berkane",
  },
  {
    id: 25,
    name: "Khénifra",
  },
  {
    id: 26,
    name: "Nador",
  },
  {
    id: 27,
    name: "Sidi Slimane",
  },
  {
    id: 28,
    name: "Fes",
  },
  {
    id: 29,
    name: "Mohammédia",
  },
  {
    id: 30,
    name: "Tangier",
  },
  {
    id: 31,
    name: "Bouskoura",
  },
  {
    id: 32,
    name: "Majorelle",
  },
  {
    id: 33,
    name: "Sidi Kacem",
  },
  {
    id: 34,
    name: "Martil",
  },
  {
    id: 35,
    name: "Soualem",
  },
  {
    id: 36,
    name: "Azrou",
  },
  {
    id: 37,
    name: "Kenitra",
  },
  {
    id: 38,
    name: "Berrchid",
  },
  {
    id: 39,
    name: "Oujda",
  },
  {
    id: 40,
    name: "Tetouan",
  },
];

const faq = [
  {
    id: 1,
    title: "Modes de paiement Ar",
    content:
      "السلام عليكم  نشكركم على وقتكم ويسعدنا الرد على أسئلتكم  يمكنكم الأداء نقدا أو بالبطاقة البنكية أو بالشيك كارفور ماركت يشكرك على ولائك ويتمنى لك يومًا سعيدًا. تحياتي،مصلحة الزبناء",
  },
  {
    id: 2,
    title: "Modes de paiement Ar",
    content:
      "السلام عليكم  نشكركم على وقتكم ويسعدنا الرد على أسئلتكم  يمكنكم الأداء نقدا أو بالبطاقة البنكية أو بالشيك كارفور ماركت يشكرك على ولائك ويتمنى لك يومًا سعيدًا. تحياتي،مصلحة الزبناء",
  },
  {
    id: 3,
    title: "Réponse Prix Fr",
    content:
      "Bonjour Madame Monsieur, Nous vous remercions du temps que vous nous avez consacré et nous serons heureux de répondre à vos questions.Nous allons nous renseigner sur le prix/ la disponibilité de ce produit dans nos magasins et revenir vers vous dès que possible. Carrefour Market vous remercie pour votre fidélité et vous souhaite une très bonne journée. Cordialement Service Relation Client",
  },
  {
    id: 4,
    title: "Réponse Prix Ar",
    content:
      "السلام عليكم،  نشكركم على وقتكم ويسعدنا الرد على أسئلتكم  سوف نستفسر عن سعر / توفر هذا المنتج في متاجرنا ونعود إليكم في أقرب وقت ممكن. من أجل المزيد من المعلومات، ندعوكم إلى زيارة أقرب متجر كارفور. كارفور ماركت يشكرك على ولائك ويتمنى لك يومًا سعيدًا. تحيات",
  },
  {
    id: 5,
    title: "Réponse Disponibilité Ar",
    content:
      "السلام عليكم،  نشكركم على وقتكم ويسعدنا الرد على أسئلتكم  سوف نستفسر عن سعر / توفر هذا المنتج في متاجرنا ونعود إليكم في أقرب وقت ممكن. من أجل المزيد من المعلومات، ندعوكم إلى زيارة أقرب متجر كارفور. كارفور ماركت يشكرك على ولائك ويتمنى لك يومًا سعيدًا. تحيات",
  },
  {
    id: 6,
    title: "Réponse Disponibilité Fr",
    content:
      "Bonjour Madame Monsieur, Nous vous remercions du temps que vous nous avez consacré et nous serons heureux de répondre à vos questions.Nous allons nous renseigner sur le prix/ la disponibilité de ce produit dans nos magasins et revenir vers vous dès que possible. Carrefour Market vous remercie pour votre fidélité et vous souhaite une très bonne journée. Cordialement Service Relation Client",
  },
  {
    id: 7,
    title: "Modes de paiement Fr",
    content:
      "Bonjour Madame Monsieur, Avant toute chose, nous vous remercions du temps que vous nous avez consacré et nous serons heureux de répondre à vos questions. Vous pouvez payer en espèce, par chèque ou par carte bancaire.Nous vous remercions pour votre fidélité et vous souhaitons une très bonne journée, Cordialement Service Relation Client",
  },
  {
    id: 8,
    title: "Modes de paiement Ar",
    content:
      "السلام عليكم  نشكركم على وقتكم ويسعدنا الرد على أسئلتكم  يمكنكم الأداء نقدا أو بالبطاقة البنكية أو بالشيك كارفور ماركت يشكرك على ولائك ويتمنى لك يومًا سعيدًا. تحياتي،مصلحة الزبناء",
  },
  {
    id: 9,
    title: "Nom du produit Ar",
    content:
      "Bonjour Madame Monsieur, Nous vous remercions du temps que vous nous avez consacré et nous serons heureux de répondre à vos questions.Nous allons nous renseigner sur le prix/ la disponibilité de ce produit dans nos magasins et revenir vers vous dès que possible. Carrefour Market vous remercie pour votre fidélité et vous souhaite une très bonne journée. Cordialement Service Relation Client",
  },
  {
    id: 10,
    title: "Nom du produit Fr",
    content:
      "السلام عليكم،  نشكركم على وقتكم ويسعدنا الرد على أسئلتكم  سوف نستفسر عن سعر / توفر هذا المنتج في متاجرنا ونعود إليكم في أقرب وقت ممكن. من أجل المزيد من المعلومات، ندعوكم إلى زيارة أقرب متجر كارفور. كارفور ماركت يشكرك على ولائك ويتمنى لك يومًا سعيدًا. تحيات",
  },
];

const groupes = [
  {
    id: 1,
    name: "Gourmet",
  },
  {
    id: 2,
    name: "Premium",
  },
  {
    id: 3,
    name: "Standard",
  },
  {
    id: 4,
    name: "Relance Express",
  },
  {
    id: 5,
    name: "Express",
  },
  {
    id: 6,
    name: "Relance mag en difficulté",
  },
  {
    id: 7,
    name: "Hypermarché",
  },
];

const marques = [
  {
    id: 1,
    name: "hyper",
  },
  {
    id: 2,
    name: "market",
  },
  {
    id: 3,
    name: "express",
  },
  {
    id: 4,
    name: "gourmet",
  },
];

const stores = [
  {
    id: 128,
    name_fr: "Carrefour Market Gourmet Rabat Zaërs",
    name_ar: null,
    latitude: 33.974401,
    longitude: -6.829218,
    street_address:
      "Route des Zaers, 3,5 km, rez de chaussée, local n° 16, Rabat, Morocco",
    city_id: 1,
    groupe_id: 1,
    category_id: 2,
    catalog_id: 7,
  },
  {
    id: 129,
    name_fr: "Carrefour Market - Moulay Ismail",
    name_ar: null,
    latitude: 33.90258,
    longitude: -5.546712,
    street_address: "i29 Bd Amir Moulay Abdallah, Meknès, Morocco",
    city_id: 2,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 130,
    name_fr: "Carrefour Market Gourmet Carré Eden",
    name_ar: null,
    latitude: 31.635046,
    longitude: -8.01115,
    street_address:
      "Carrefour Market Carré Eden, Centre commerciale Carré Eden, Av. Mohammed V, Marrakech 40000, Morocco",
    city_id: 3,
    groupe_id: 1,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 131,
    name_fr: "Carrefour Market Anfa",
    name_ar: null,
    latitude: 33.577225,
    longitude: -7.674152,
    street_address:
      "H8GG+V8F, Bd Abdelhadi Boutaleb, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 2,
    category_id: 2,
    catalog_id: 9,
  },
  {
    id: 132,
    name_fr: "Carrefour Gourmet",
    name_ar: null,
    latitude: 33.590783,
    longitude: -7.646146,
    street_address: "H9R3+8G9, Av. Ahmed Charci, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 1,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 133,
    name_fr: "Carrefour Market la Fontaine",
    name_ar: null,
    latitude: 31.628325,
    longitude: -8.002604,
    street_address:
      "Carrefour Market la Fontaine, Résidence la fontaine, N°1 Bd Al Yarmouk, Marrakech 40000, Morocco",
    city_id: 3,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 134,
    name_fr: "Carrefour Market Menara Mall",
    name_ar: null,
    latitude: 31.618653,
    longitude: -8.009068,
    street_address: "JX9R+F9H, Marrakesh 40000, Morocco",
    city_id: 5,
    groupe_id: 2,
    category_id: 2,
    catalog_id: 9,
  },
  {
    id: 135,
    name_fr: "Carrefour Market Fès Immouzer",
    name_ar: null,
    latitude: 34.021947,
    longitude: -4.997487,
    street_address: "22C2+WW4, Fes 30050, Morocco",
    city_id: 6,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 136,
    name_fr: "Carrefour Market Sidi Said Meknès",
    name_ar: null,
    latitude: 33.892918,
    longitude: -5.575377,
    street_address: "VCVF+5PX, Meknes, Morocco",
    city_id: 2,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 137,
    name_fr: "Carrefour Market Iberia",
    name_ar: null,
    latitude: 35.782651,
    longitude: -5.81976,
    street_address: "Q5MJ+G5P Collège Maa Al Aynine, Tanger, Morocco",
    city_id: 8,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 138,
    name_fr: "Carrefour Market Ibn Batouta",
    name_ar: null,
    latitude: 35.777332,
    longitude: -5.802087,
    street_address: "24 Rue Offenbach، Tanger, Morocco",
    city_id: 8,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 139,
    name_fr: "Carrefour Market Anfa Place",
    name_ar: null,
    latitude: 33.598475,
    longitude: -7.665058,
    street_address:
      "AnfaPLace, H8XP+C2W, Bd de la Corniche, Casablanca, Morocco",
    city_id: 4,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 140,
    name_fr: "Carrefour Market Le barreau Agadir",
    name_ar: null,
    latitude: 30.402653,
    longitude: -9.578863,
    street_address: "CC3C+3H, Agadir 80000, Morocco",
    city_id: 9,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 141,
    name_fr: "Carrefour Market El Jadida 2 Najd",
    name_ar: null,
    latitude: 33.227702,
    longitude: -8.506972,
    street_address: "6FHV+36J, Av. Othmane Ibn Affane, El Jadida, Morocco",
    city_id: 10,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 142,
    name_fr: "Carrefour Market Dar Bouazza",
    name_ar: null,
    latitude: 33.513989,
    longitude: -7.818234,
    street_address: "G57J+HMX, Tamaris, Morocco",
    city_id: 11,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 143,
    name_fr: "Carrefour Market Essaouira",
    name_ar: null,
    latitude: 31.495889,
    longitude: -9.752354,
    street_address: "F6WX+83H, Essaouira, Morocco",
    city_id: 12,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 144,
    name_fr: "Carrefour Market Wifak",
    name_ar: null,
    latitude: 33.929593,
    longitude: -6.928873,
    street_address: "W3HC+VF8, Temara, Morocco",
    city_id: 13,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 145,
    name_fr: "Carrefour Market Maari",
    name_ar: null,
    latitude: 33.580151,
    longitude: -7.640697,
    street_address: "63 Rue Al Fourate، Dar-el-Beida 20330, Morocco",
    city_id: 14,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 146,
    name_fr: "Carrefour Market Yacoub El Mansour",
    name_ar: null,
    latitude: 33.573866,
    longitude: -7.644543,
    street_address:
      "37 Rue Ibnou Al Kattan Maarif Extension, Casablanca, Morocco",
    city_id: 4,
    groupe_id: 2,
    category_id: 2,
    catalog_id: 9,
  },
  {
    id: 147,
    name_fr: "Carrefour Market Taddart",
    name_ar: null,
    latitude: 33.55456,
    longitude: -7.626517,
    street_address:
      "Résidence Arriad, Lotissement Yasmine 2, Piste Taddarte, Casablanca, Morocco",
    city_id: 4,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 148,
    name_fr: "Carrefour Market Panoramique",
    name_ar: null,
    latitude: 33.548156,
    longitude: -7.628718,
    street_address: "558 Bd Panoramique, Casablanca, Morocco",
    city_id: 4,
    groupe_id: 2,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 149,
    name_fr: "Carrefour Market Hassan 1er",
    name_ar: null,
    latitude: 30.410995,
    longitude: -9.561515,
    street_address: "3, Agadir 80060, Morocco",
    city_id: 9,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 150,
    name_fr: "Carrefour Market Lissassfa",
    name_ar: null,
    latitude: 33.537958,
    longitude: -7.680469,
    street_address: "G8Q9+5MV, Rue H, Casablanca 20260, Morocco",
    city_id: 4,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 151,
    name_fr: "Carrefour Market Abdelmoumen",
    name_ar: null,
    latitude: 33.569126,
    longitude: -7.626219,
    street_address:
      "Angle Boulvard Abldelmoumen et, Bd Anoual, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 152,
    name_fr: "Carrefour Market Kénitra 1",
    name_ar: null,
    latitude: 34.259699,
    longitude: -6.581979,
    street_address: "55 Rue Moulay Abdellah, Kénitra 14000, Morocco",
    city_id: 15,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 153,
    name_fr: "Carrefour Market Val Fleuri",
    name_ar: null,
    latitude: 33.57413,
    longitude: -7.636124,
    street_address: "7 Rue Henri Murger, Casablanca 20390, Morocco",
    city_id: 4,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 154,
    name_fr: "Carrefour Market Mansouria - Mohammedia",
    name_ar: null,
    latitude: 33.730498,
    longitude: -7.329847,
    street_address: "PMJC+64M, Mohammedia, Morocco",
    city_id: 16,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 155,
    name_fr: "Carrefour Market Al Manal",
    name_ar: null,
    latitude: 33.975968,
    longitude: -6.890113,
    street_address: "Rue Alaklak, Lot Al Manzeh CYM, Label'Vie, Rabat, Morocco",
    city_id: 1,
    groupe_id: 3,
    category_id: 2,
    catalog_id: 7,
  },
  {
    id: 156,
    name_fr: "Carrefour Market - Plaisance",
    name_ar: null,
    latitude: 33.900189,
    longitude: -5.504493,
    street_address: "VFXW+X48, Ex Palais Assourour, Meknès, Morocco",
    city_id: 2,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 157,
    name_fr: "Carrefour Market Khemisset",
    name_ar: null,
    latitude: 33.826459,
    longitude: -6.091153,
    street_address: "RWG5+MG5, Av. Mohamed V, Khémisset, Morocco",
    city_id: 17,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 158,
    name_fr: "Carrefour Market Kasba",
    name_ar: null,
    latitude: 33.698091,
    longitude: -7.390758,
    street_address: "MJX5+6PM, Mohammedia, Morocco",
    city_id: 16,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 159,
    name_fr: "Carrefour Supermarché Tétouan Wilaya",
    name_ar: null,
    latitude: 35.585179,
    longitude: -5.341424,
    street_address: "4 Av. Le Caire, Tétouan 93000, Morocco",
    city_id: 18,
    groupe_id: 3,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 160,
    name_fr: "Carrefour Express Bourgogne",
    name_ar: null,
    latitude: 33.59839,
    longitude: -7.642024,
    street_address: "H9X5+94G, Bd de Bourgogne, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 3,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 161,
    name_fr: "Carrefour Market Ouarzazate",
    name_ar: null,
    latitude: 30.919996,
    longitude: -6.919413,
    street_address: "W3CJ+262, Av. Mohammed V, Ouarzazate 45000, Morocco",
    city_id: 19,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 162,
    name_fr: "Carrefour Market Hassan",
    name_ar: null,
    latitude: 34.021161,
    longitude: -6.827101,
    street_address: "43 Av. Moulay Ismail, Rabat, Morocco",
    city_id: 1,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 163,
    name_fr: "Carrefour Market Safi",
    name_ar: null,
    latitude: 32.293032,
    longitude: -9.234444,
    street_address: "7QV8+46Q, Rue Taib Ben Hima, BenHimaSafi, Morocco",
    city_id: 20,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 164,
    name_fr: "Carrefour Market Sala Al Jadida",
    name_ar: null,
    latitude: 33.996215,
    longitude: -6.741917,
    street_address: "X7W5+C9C, Av. Hassan II, Salé, Morocco",
    city_id: 21,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 165,
    name_fr: "Carrefour Market Settat",
    name_ar: null,
    latitude: 32.99882,
    longitude: -7.6193,
    street_address:
      "Carrefour Market Settat, Angle Rue Abdelmoumen et Rue Général Monier، Settat, Morocco",
    city_id: 22,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 166,
    name_fr: "Carrefour Market",
    name_ar: null,
    latitude: 32.331724,
    longitude: -6.352882,
    street_address:
      "carrefour Bd 20 Aout & Qr Charaf-23000-،, Béni Mellal, Morocco",
    city_id: 23,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 167,
    name_fr: "Carrefour Market Souissi",
    name_ar: null,
    latitude: 33.982116,
    longitude: -6.828961,
    street_address:
      "Angle Mehdi Ben Barka et Bd Mohammed VI Rabat, Rabat, Morocco",
    city_id: 1,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 168,
    name_fr: "Carrefour Market Berkane",
    name_ar: null,
    latitude: 34.931122,
    longitude: -2.309454,
    street_address: "WMJR+C6J, Berkane, Morocco",
    city_id: 24,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 169,
    name_fr: "Carrefour Market Ziraoui",
    name_ar: null,
    latitude: 33.597028,
    longitude: -7.629585,
    street_address: "H9WC+R49, Bd Ziraoui, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 170,
    name_fr: "Carrefour Market Khénifra",
    name_ar: null,
    latitude: 32.944081,
    longitude: -5.660143,
    street_address: "W8VQ+MRF, P24, Khénifra, Morocco",
    city_id: 25,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 171,
    name_fr: "Carrefour Market Nador",
    name_ar: null,
    latitude: 35.15932,
    longitude: -2.930545,
    street_address:
      "Carrefour Market Nador, Route principale - Route Tawima, Nador, Morocco",
    city_id: 26,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 172,
    name_fr: "Carrefour Market Sidi Slimane",
    name_ar: null,
    latitude: 34.259871,
    longitude: -5.922108,
    street_address: "64 Av. Hassan II, Sidi Slimane, Morocco",
    city_id: 27,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 173,
    name_fr: "Carrefour Market Fès Megamarket",
    name_ar: null,
    latitude: 34.001529,
    longitude: -5.010589,
    street_address: "2X2Q+JQ Fes, Morocco",
    city_id: 6,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 174,
    name_fr: "Carrefour Market ALIA",
    name_ar: null,
    latitude: 33.685818,
    longitude: -7.378298,
    street_address: "MJPC+7M5, Bd de Riyad, Mohammédia, Morocco",
    city_id: 16,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 175,
    name_fr: "Carrefour Market Le Parc",
    name_ar: null,
    latitude: 33.706427,
    longitude: -7.3952,
    street_address:
      "Carrefour Market Le Parc, Angle Avenue du Parc et, Av. du Parc, Mohammédia, Morocco",
    city_id: 16,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 176,
    name_fr: "Carrefour Express Tanger Malabata",
    name_ar: null,
    latitude: 35.763105,
    longitude: -5.819272,
    street_address: "Q57J+6GG, Tangier 90060, Morocco",
    city_id: 30,
    groupe_id: 3,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 177,
    name_fr: "Carrefour Market Bouskoura Ville",
    name_ar: null,
    latitude: 33.46184,
    longitude: -7.643668,
    street_address: "F964+JMP, P3011, Bouskoura, Morocco",
    city_id: 31,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 178,
    name_fr: "Carrefour Market Bellerive",
    name_ar: null,
    latitude: 33.596775,
    longitude: -7.592972,
    street_address: "HCW4+PP5, Bd Emile Zola, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 179,
    name_fr: "Carrefour Market Semlalia",
    name_ar: null,
    latitude: 31.648802,
    longitude: -8.00962,
    street_address:
      "Carrefour Market Semlalia, Lotissement Sinko Ghiliz Wilaya de Marrakech, Marrakech 40000, Morocco",
    city_id: 3,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 180,
    name_fr: "Carrefour Market Riad",
    name_ar: null,
    latitude: 33.962285,
    longitude: -6.877161,
    street_address: "CC Riad, 1 Av. Annakhil, Rabat, Morocco",
    city_id: 1,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 181,
    name_fr: "Carrefour Market Volubilis",
    name_ar: null,
    latitude: 35.765965,
    longitude: -5.808848,
    street_address:
      "Boulevard Moulay Ismail, Immeuble Giraud Volubilus, Tanger 90060, Morocco",
    city_id: 8,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 182,
    name_fr: "Carrefour Market Hassan 2",
    name_ar: null,
    latitude: 30.414078,
    longitude: -9.593491,
    street_address: "CC74+JJC, Agadir 80000, Morocco",
    city_id: 9,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 183,
    name_fr: "Carrefour Market Label Shop",
    name_ar: null,
    latitude: 33.572968,
    longitude: -7.619978,
    street_address: "77 Rue Abou Alâa Zahr, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 184,
    name_fr: "Carrefour Market Kenitra Mimosas",
    name_ar: null,
    latitude: 34.252977,
    longitude: -6.594699,
    street_address: "Rue Misr, Résidence Belgout, Kénitra, Morocco",
    city_id: 15,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 185,
    name_fr: "Carrefour Market Shem's",
    name_ar: null,
    latitude: 34.002317,
    longitude: -6.852044,
    street_address: "Cité Ibn Sina, N°1, Rabat, Morocco",
    city_id: 1,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 186,
    name_fr: "Carrefour Market Gauthier 2",
    name_ar: null,
    latitude: 33.589748,
    longitude: -7.629727,
    street_address: "2 Rue Taha Hussein, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 187,
    name_fr: "Carrefour Market Oqba",
    name_ar: null,
    latitude: 34.005674,
    longitude: -6.847444,
    street_address: "n18 Rue Al Achaari, Rabat, Morocco",
    city_id: 1,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 188,
    name_fr: "Carrefour Market Kenitra Maamoura",
    name_ar: null,
    latitude: 34.256924,
    longitude: -6.582434,
    street_address: "7C48+PX9, Av. Moulay Abderrahmane, Kénitra, Morocco",
    city_id: 15,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 189,
    name_fr: "Carrefour Express Victoria",
    name_ar: null,
    latitude: 33.412842,
    longitude: -12.158318,
    street_address: "8C59CR7R+4M",
    city_id: 1,
    groupe_id: 4,
    category_id: 4,
    catalog_id: 7,
  },
  {
    id: 190,
    name_fr: "Carrefour Market Fès Atlas",
    name_ar: null,
    latitude: 34.030404,
    longitude: -4.993325,
    street_address: "Zone Industrielle Dahr Khamiss, Fès 30050, Morocco",
    city_id: 6,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 191,
    name_fr: "Carrefour Market Oulfa",
    name_ar: null,
    latitude: 33.562209,
    longitude: -7.668984,
    street_address:
      "52, Angle Boulevard Oued Oum Rabia et, Rte Moulay Thami, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 192,
    name_fr: "CARREFOUR BETTANA market",
    name_ar: null,
    latitude: 34.031518,
    longitude: -6.802522,
    street_address:
      "Quartier Bettana, Angle Avenue Mediouna et Rue Ouarzazate, Immeuble YA ZAMANE 6, Salé, Morocco",
    city_id: 21,
    groupe_id: 3,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 193,
    name_fr: "Carrefour Express 2 Mars",
    name_ar: null,
    latitude: 33.573612,
    longitude: -7.61937,
    street_address: "73 Rue Abou Alâa Zahr, Casablanca 20000, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 194,
    name_fr: "Carrefour Market Madagascar",
    name_ar: null,
    latitude: 34.014287,
    longitude: -6.850808,
    street_address: "49 Av. Madagascar, Rabat, Morocco",
    city_id: 1,
    groupe_id: 3,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 195,
    name_fr: "Carrefour Market Majorelle",
    name_ar: null,
    latitude: 31.640673,
    longitude: -8.001433,
    street_address: "1 Rue Yves St Laurent, Majorelle، 40000, Morocco",
    city_id: 1,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 196,
    name_fr: "Carrefour Express Bir Anzarane",
    name_ar: null,
    latitude: 33.584068,
    longitude: -7.644536,
    street_address: "H9M4+95R, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 197,
    name_fr: "Carrefour Express Beni Makada Tanger",
    name_ar: null,
    latitude: 35.743563,
    longitude: -5.806563,
    street_address: "P5VV+C96, Tangier 90060, Morocco",
    city_id: 30,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 198,
    name_fr: "Carrefour Market Fès Megamarket/",
    name_ar: null,
    latitude: 34.001529,
    longitude: -5.010589,
    street_address: "2X2Q+JQ Fes, Morocco",
    city_id: 6,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 199,
    name_fr: "Carrefour Market Gauthier Expresse",
    name_ar: null,
    latitude: 33.589894,
    longitude: -7.631541,
    street_address: "35 Av. Hassan Souktani, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 200,
    name_fr: "Carrefour Express Casa Av. Hassan Seghir",
    name_ar: null,
    latitude: 33.594563,
    longitude: -7.610438,
    street_address: "H9VQ+RRF, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 201,
    name_fr: "Carrefour Express Casa Route Al Ouahda",
    name_ar: null,
    latitude: 33.608813,
    longitude: -7.545063,
    street_address: "JF53+GX2, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 202,
    name_fr: "Carrefour Express La Gironde",
    name_ar: null,
    latitude: 33.584924,
    longitude: -7.599908,
    street_address: "63 Bd de la Gironde, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 203,
    name_fr: "Carrefour Express Mers Sultan",
    name_ar: null,
    latitude: 33.584508,
    longitude: -7.615924,
    street_address: "196 Av. Mers Sultan, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 204,
    name_fr: "Carrefour Express Rachidi",
    name_ar: null,
    latitude: 33.593402,
    longitude: -7.627187,
    street_address: "H9VF+952, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 205,
    name_fr: "Carrefour Express Sidi Kacem",
    name_ar: null,
    latitude: 34.220824,
    longitude: -5.709987,
    street_address: "67CR+82R, Sidi Kacem, Morocco",
    city_id: 33,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 206,
    name_fr: "Carrefour Express Martil",
    name_ar: null,
    latitude: 35.615604,
    longitude: -5.273233,
    street_address: "JP8G+7QP, Martil, Morocco",
    city_id: 34,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 207,
    name_fr: "Carrefour Express La Gironde Addalia",
    name_ar: null,
    latitude: 33.578693,
    longitude: -7.596041,
    street_address: "HCH3+FM7, Rue Al Ismailiya،, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 208,
    name_fr: "Carrefour Express Romandie",
    name_ar: null,
    latitude: 33.5855,
    longitude: -7.646801,
    street_address:
      "Angle Boulevard Bir Anzarane et Rue El Azrak Ahmed, Romandie II, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 209,
    name_fr: "Carrefour Express Mohammed V",
    name_ar: null,
    latitude: 33.591623,
    longitude: -7.59468,
    street_address:
      "649 bd mohammed 5 belvédère résidence chaouia 2 eme etage, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 210,
    name_fr: "Carrefour Express Bourgogne",
    name_ar: null,
    latitude: 33.59839,
    longitude: -7.639836,
    street_address: "H9X6+933, Bd de Bourgogne, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 211,
    name_fr: "Carrefour Express Medina",
    name_ar: null,
    latitude: 34.021014,
    longitude: -6.842357,
    street_address: "6 Av. Al Maghrib Al Arabi, Rabat, Morocco",
    city_id: 1,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 212,
    name_fr: "Carrefour Market Le barreau Agadir",
    name_ar: null,
    latitude: 30.402653,
    longitude: -9.578863,
    street_address: "CC3C+3H, Agadir 80000, Morocco",
    city_id: 9,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 213,
    name_fr: "Carrefour Express Mohammedia Sebta",
    name_ar: null,
    latitude: 33.694733,
    longitude: -7.380659,
    street_address:
      "Carrefour Market Mohammedia Sebta, Bd de Sebta, Mohammédia, Morocco",
    city_id: 16,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 214,
    name_fr: "Carrefour Market Beausejour",
    name_ar: null,
    latitude: 33.566949,
    longitude: -7.651309,
    street_address: "51 Rue Al Khouzame, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 215,
    name_fr: "Carrefour Express Oasis",
    name_ar: null,
    latitude: 33.560143,
    longitude: -7.630507,
    street_address: "8 Rue des Tabors, Casablanca, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 216,
    name_fr: "Carrefour Market La Villette",
    name_ar: null,
    latitude: 33.589108,
    longitude: -7.577906,
    street_address:
      "HCQC+GP8, Rue Abou Youssef El Mesdaghi, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 217,
    name_fr: "Carrefour Market Cadi Ayad",
    name_ar: null,
    latitude: 30.419203,
    longitude: -9.578012,
    street_address:
      "303, 3eme étage, Immeuble, Lokman Av. Kadi Ayad, Agadir 80000, Morocco",
    city_id: 9,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 218,
    name_fr: "Carrefour Market Hassan 2 Mohammedia",
    name_ar: null,
    latitude: 33.714371,
    longitude: -7.344572,
    street_address: "PM74+M6G, Bd Hassan II, Mohammédia, Morocco",
    city_id: 16,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 219,
    name_fr: "Carrefour Market Kenitra Av Moulay Abdelaziz",
    name_ar: null,
    latitude: 34.257801,
    longitude: -6.592018,
    street_address: "93 Av. Moulay Abdelazziz, Kénitra, Morocco",
    city_id: 15,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 220,
    name_fr: "Carrefour Market Descartes",
    name_ar: null,
    latitude: 33.987278,
    longitude: -6.849476,
    street_address: "74 Avenue Jaafar Essadik, Rabat 10000, Morocco",
    city_id: 1,
    groupe_id: 4,
    category_id: 2,
    catalog_id: 7,
  },
  {
    id: 221,
    name_fr: "Carrefour Market Sidi Said Meknès/",
    name_ar: null,
    latitude: 33.892918,
    longitude: -5.575377,
    street_address: "VCVF+5PX, Meknes, Morocco",
    city_id: 2,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 222,
    name_fr: "Carrefour Market Agadir El Houda",
    name_ar: null,
    latitude: 30.400267,
    longitude: -9.534051,
    street_address: "Résidence Jenine 1, Rue Kerdous, Agadir 80000, Morocco",
    city_id: 9,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 223,
    name_fr: "Carrefour Market Palmeraie",
    name_ar: null,
    latitude: 31.681722,
    longitude: -7.98387,
    street_address: "M2J8+MF Marrakesh, Morocco",
    city_id: 5,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 224,
    name_fr: "Carrefour Express Moulay Youssef Tanger",
    name_ar: null,
    latitude: 35.77086,
    longitude: -5.812527,
    street_address: "24 Av. Moulay Youssef, Tanger 90000, Morocco",
    city_id: 8,
    groupe_id: 4,
    category_id: 4,
    catalog_id: null,
  },
  {
    id: 225,
    name_fr: "Carrefour Market Deroua",
    name_ar: null,
    latitude: 33.394271,
    longitude: -7.53406,
    street_address: "9FV8+M9F, Morocco",
    city_id: 1,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 226,
    name_fr: "Carrefour Market Mehdi Ben Barka",
    name_ar: null,
    latitude: 33.949628,
    longitude: -6.868045,
    street_address: "W4XJ+R9W, Rabat, Morocco",
    city_id: 1,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 227,
    name_fr: "Carrefour Market Avenue des FAR Tanger",
    name_ar: null,
    latitude: 35.753624,
    longitude: -5.833374,
    street_address: "1, Tanger 90060, Morocco",
    city_id: 8,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 228,
    name_fr: "Carrefour Market Champs de Course Fès",
    name_ar: null,
    latitude: 34.033201,
    longitude: -5.016625,
    street_address: "2XMM+79H, Fes 30050, Morocco",
    city_id: 6,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 229,
    name_fr: "Carrefour Market Had Soualem",
    name_ar: null,
    latitude: 33.422773,
    longitude: -7.852515,
    street_address: "C4FX+324, Soualem, Morocco",
    city_id: 35,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 230,
    name_fr: "Carrefour Market",
    name_ar: null,
    latitude: 33.446593,
    longitude: -5.230377,
    street_address: "369 RUE 4, Azrou, Morocco",
    city_id: 36,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 231,
    name_fr: "Carrefour Market Océan",
    name_ar: null,
    latitude: 34.023119,
    longitude: -6.850133,
    street_address: "12 Rue Belgrade, Rabat 10040, Morocco",
    city_id: 1,
    groupe_id: 4,
    category_id: 2,
    catalog_id: 7,
  },
  {
    id: 232,
    name_fr: "Carrefour Market Ain Sebaa",
    name_ar: null,
    latitude: 33.602032,
    longitude: -7.528936,
    street_address: "JF2C+Q3G Aïn Sebaâ Park, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 6,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 233,
    name_fr: "Carrefour Market Ville Verte Casablanca",
    name_ar: null,
    latitude: 33.497863,
    longitude: -7.607603,
    street_address: "Universite Internationale, Bouskoura, Morocco",
    city_id: 31,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 234,
    name_fr: "Carrefour Market Ain Sebaa",
    name_ar: null,
    latitude: 33.607585,
    longitude: -7.536863,
    street_address:
      "Bb chefchaouni, angle rue Abdelhamid Bnou Badis, 3éme étage, n° 14, près du ront, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 235,
    name_fr: "Carrefour Market",
    name_ar: null,
    latitude: 33.90747,
    longitude: -6.923258,
    street_address: "W34G+XFX, Temara, Morocco",
    city_id: 13,
    groupe_id: 6,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 236,
    name_fr: "Carrefour Market la Résistance",
    name_ar: null,
    latitude: 33.584356,
    longitude: -7.6105,
    street_address: "97 Bd de la Liberté, Casablanca 20100, Morocco",
    city_id: 4,
    groupe_id: 6,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 237,
    name_fr: "Carrefour Market Abdelkrim Khattabi Marrakech",
    name_ar: null,
    latitude: 31.633119,
    longitude: -8.016488,
    street_address:
      "Immeuble rokia 'A' Appt 19 étage 3, Marrakech 40000, Morocco",
    city_id: 3,
    groupe_id: 6,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 238,
    name_fr: "Carrefour Market Kénitra",
    name_ar: null,
    latitude: 34.261895,
    longitude: -6.587388,
    street_address: "7C67+M44, Kenitra, Morocco",
    city_id: 15,
    groupe_id: 6,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 239,
    name_fr: "Carrefour Market El Jadida 2 Najd",
    name_ar: null,
    latitude: 33.227702,
    longitude: -8.506972,
    street_address: "6FHV+36J, Av. Othmane Ibn Affane, El Jadida, Morocco",
    city_id: 10,
    groupe_id: 6,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 240,
    name_fr: "Carrefour Dar Bouazza",
    name_ar: null,
    latitude: 33.517166,
    longitude: -7.799547,
    street_address: "G682+V8H, Tamaris, Morocco",
    city_id: 11,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 241,
    name_fr: "Carrefour Agadir",
    name_ar: null,
    latitude: 30.389265,
    longitude: -9.510129,
    street_address: "9FQQ+XRC, 110-4 located in, Agadir 80000, Morocco",
    city_id: 9,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 242,
    name_fr: "Carrefour Market Marrakech Massira 3",
    name_ar: null,
    latitude: 31.632746,
    longitude: -8.071732,
    street_address: "JWMH+38J, Marrakesh, Morocco",
    city_id: 5,
    groupe_id: 6,
    category_id: 2,
    catalog_id: null,
  },
  {
    id: 243,
    name_fr: "Carrefour Berrechid",
    name_ar: null,
    latitude: 33.258847,
    longitude: -7.580766,
    street_address: "7C59+FQC, Rte de Khouribga, Berrchid, Morocco",
    city_id: 38,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 244,
    name_fr: "Carrefour Al Mazar",
    name_ar: null,
    latitude: 31.592516,
    longitude: -7.9871,
    street_address: "H2V6+4W6, Marrakesh, Morocco",
    city_id: 5,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 245,
    name_fr: "Carrefour Oujda",
    name_ar: null,
    latitude: 34.659458,
    longitude: -1.906292,
    street_address: "M35V+PFG, Rue Sounna, Oujda, Morocco",
    city_id: 39,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 246,
    name_fr: "Carrefour Socco Alto",
    name_ar: null,
    latitude: 35.781454,
    longitude: -5.840988,
    street_address: "Socco Alto, Avenue Banafsaj, Tangier 90040, Morocco",
    city_id: 30,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 247,
    name_fr: "Carrefour Sidi Maarouf",
    name_ar: null,
    latitude: 33.535976,
    longitude: -7.642066,
    street_address: "G9P5+84J, Casablanca, Morocco",
    city_id: 4,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 248,
    name_fr: "Carrefour Sale",
    name_ar: null,
    latitude: 34.058762,
    longitude: -6.802177,
    street_address: "355X+H5X, Salé, Morocco",
    city_id: 21,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 249,
    name_fr: "Carrefour Targa",
    name_ar: null,
    latitude: 31.650724,
    longitude: -8.059146,
    street_address:
      "Croisement route Targa et Boulevard Laâyoune, Marrakech 40140, Morocco",
    city_id: 3,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 250,
    name_fr: "Carrefour Borj Fes",
    name_ar: null,
    latitude: 34.046288,
    longitude: -4.994645,
    street_address: "Centre Commercial Borj Fès, Fès, 30050, Morocco",
    city_id: 6,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 251,
    name_fr: "Carrefour Tetouan",
    name_ar: null,
    latitude: 35.57836,
    longitude: -5.333915,
    street_address: "HMH8+6F, Tetouan, Morocco",
    city_id: 18,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 252,
    name_fr: "Carrefour Market Palmier",
    name_ar: null,
    latitude: 33.582329,
    longitude: -7.628543,
    street_address: "Boulevard 9 Avril, Casablanca 20250, Morocco",
    city_id: 4,
    groupe_id: 4,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 253,
    name_fr: "Carrefour Temara",
    name_ar: null,
    latitude: 33.908334,
    longitude: -6.938794,
    street_address: "W356+78W, Temara, Morocco",
    city_id: 13,
    groupe_id: 7,
    category_id: 1,
    catalog_id: null,
  },
  {
    id: 254,
    name_fr: "Carrefour Market Malraux",
    name_ar: null,
    latitude: 34.015668,
    longitude: -6.845539,
    street_address: "4 Rue Ibn Al Khatib، Rabat, Morocco",
    city_id: 1,
    groupe_id: 6,
    category_id: 2,
    catalog_id: null,
  },
];

const messageTemplates = [
  {
    textFr: "📍 Carrefour autour de moi",
    textAr: "📍 البحث عن كارفور بالقرب مني",
    descriptionAr: `يرجى مشاركة موقعك معنا📍`,
    descriptionFr: "Merci de nous partager votre localisation📍",
  },
  {
    textFr: "📒 Recevoir le catalogue",
    textAr: "📒 استلام الكتالوج",
    descriptionAr: `يرجى مشاركة موقعك معنا📍`,
    descriptionFr: "Merci de nous partager votre localisation📍",
  },
  {
    textFr: "🛍 s'abonner à nos pages ou visiter nos sites web",
    textAr: "🛍 الاشتراك في صفحاتنا و  زيارة موقعنا الإلكتروني",
    descriptionAr: "",
    descriptionFr: "",
  },
  {
    textFr: "⚠️ Soumettre une réclamation",
    textAr: "⚠️ تقديم شكوى",
    descriptionAr: "هل يمكنكم تزويدنا بمزيد من المعلومات؟ 🤔",
    descriptionFr: "Pourriez-vous nous en dire plus ? 🤔",
  },
  {
    textFr: "📦 Être livré chez-soi",
    textAr: "📦 التوصيل إلى المنزل",
    descriptionAr: `من أجل الوصول إلى مواقعنا الإلكترونية ، ندعوك للنقر على الروابط أدناه 👇
            
كارفور: 
https://bit.ly/3A2xR2H
كارفور ماركت، كارفور إكسبرس، وكارفور جورميه.
https://bit.ly/3ofxlMe`,
    descriptionFr: `Afin d’accéder à nos sites web, nous vous invitons à appuyer sur les liens ci-dessous 👇
Carrefour: https://bit.ly/3A2xR2H
Carrefour Market,  Carrefour Express et Carrefour Gourmet: https://bit.ly/3ofxlMe`,
  },
  {
    textFr: "💳 S'inscrire à notre programme de fidélité",
    textAr: "💳 الاشتراك في برنامج الولاء FID",
    descriptionAr: `للاشتراك في برنامج الولاء الخاص بنا، ندعوك لتحميل تطبيق كارفور المغرب
الرابط: https://onelink.to/a95vau`,
    descriptionFr: `Pour vous abonner à notre programme de fidélité, nous vous invitons à télécharger l'application Carrefour Maroc
Lien : https://onelink.to/a95vau`,
  },
  {
    textFr: "🏢 Demandes d'emploi",
    textAr: "🏢 طلبات العمل",
    descriptionAr: `نشكرك على اهتمامك بشركتنا. سنكون سعداء للإجابة على أي أسئلتك. يرجى إرسال سيرتك الذاتية إلى البريد الإلكتروني التالي: Jobs@labelvie.ma
    نحن نود إعلامك بأن خدمة الموارد البشرية ستتصل بك فور توفر فرصة تتناسب مع ملفك الشخصي. نتمنى لك النجاح في حياتك المهنية ونشكرك على وفائك.`,
    descriptionFr: `Nous vous remercions de l'intérêt que vous portez à notre entreprise. Nous serions ravis de répondre à vos questions. Nous vous prions de bien vouloir envoyer votre CV à l'adresse mail suivante : 
    Jobs@labelvie.ma
    Nous tenons à vous informer que notre service RH vous contactera dès qu'une opportunité correspondant à votre profil se présentera. Nous vous souhaitons beaucoup de succès dans votre carrière et vous remercions pour votre fidélité.`,
  },
  {
    textFr: "🕐 Horaires d'ouverture et fermeture des magasins",
    textAr: "🕐 ساعات عمل المتاجر وإغلاقها",
    descriptionAr:
      "يتم فتح متاجرنا كل يوم من الساعة 9:00 صباحًا حتى الساعة 6:30 مساءً، ومن الساعة 7:30 مساءً حتى الساعة 11:00 مساءً.",
    descriptionFr:
      "Nos magasins sont ouverts chaque jour de 9h00 à 18h30 et  de 19h30–23h00",
  },
  {
    textFr: "🏦 Pièces à fournir pour le crédit Eléctro",
    textAr: "🏦 المستندات المطلوبة للحصول على قرض إلكترو.",
    descriptionAr: `نشكرك على وقتك وسعداء بالإجابة على أي استفسارات لديك. للاستفادة من القرض المجاني، سيتعين عليك تقديم الوثائق التالية: بطاقة الهوية الوطنية، نموذج شيك أو شهادة تحقق من الهوية البنكية المطلوبة، فاتورة هاتف أو كهرباء، آخر 3 كشوفات بنكية، بالإضافة إلى الوثائق المطلوبة حسب نوع الدخل:
  
  - للموظفين: آخرين كشوفات الراتب وشهادة العمل.
  - للعاملين: شهادة التزام أو شهادة الراتب.
  - للمتقاعدين: آخرين إشعارين بالتقاعد.
  - للعمال المستقلين: بطاقة مهنية وآخر إشعار بالضرائب التجارية.
  - للتجار: نسخة من الاستمارة 7 للسجل التجاري (أقل من 3 أشهر).
  
  نشكركم من القلب على وفائكم لكارفور ونتمنى لكم يوماً ممتعاً. للمزيد من المعلومات، يرجى الاتصال بنا على الرقم التالي: 05 29 045 777.`,
    descriptionFr: `Nous vous remercions de votre temps et nous sommes heureux de répondre à vos questions. Afin de bénéficier du prêt gratuit, vous devrez fournir les documents suivants: carte d'identité nationale, modèle de chèque ou certificat d'identification bancaire requis, facture de téléphone ou d'électricité, les 3 derniers relevés bancaires, ainsi que les documents requis selon le type de revenu :
  
  Pour les salariés : les deux derniers bulletins de salaire et un certificat de travail.
  Pour les employés : une attestation d'engagement ou un certificat de salaire.
  Pour les retraités : les deux derniers avis d'acompte de pension.
  Pour les travailleurs indépendants : la carte professionnelle et le dernier avis d'imposition sur les taxes commerciales.
  Pour les commerçants : une copie du formulaire 7 du registre du commerce (moins de 3 mois).
  Nous tenons à vous remercier de tout cœur pour votre fidélité à Carrefour et vous souhaitons une excellente journée.
  pour plus d'information merci de nous contacter sur le numero suivant: 05 29 045 777`,
  },
  {
    textFr: "💰 Modes de paiement acceptés par Carrefour",
    textAr: "💰ما طرق الدفع التي يقبلها كارفور ؟",
    descriptionAr: `السلام عليكم
  نشكركم على وقتكم ويسعدنا الرد على أسئلتكم 
  يمكنكم الأداء نقدا أو بالبطاقة البنكية أو بالشيك
             
  كارفور ماركت يشكرك على ولائك ويتمنى لك يومًا سعيدًا.
  تحياتي،
  مصلحة الزبناء`,
    descriptionFr: `Bonjour Madame Monsieur,
  
  Avant toute chose, nous vous remercions du temps que vous nous avez consacré et nous serons heureux de répondre à vos questions.
  Vous pouvez payer en espèce, par chèque ou par carte bancaire.        
  
  Nous vous remercions pour votre fidélité et vous souhaitons une très bonne journée,
      
  Cordialement
  Service Relation Client`,
  },
];

const dataSeeder = async () => {
  // DATA SEED for groupe table
  // groupes.forEach(async (groupe) => {
  //   await prisma.group.create({
  //     data: {
  //       name: groupe.name,
  //     },
  //   });
  // });
  // // DATA SEED for Cities

  // cities.forEach(async (city) => {
  //   await prisma.city.create({
  //     data: {
  //       name: city.name,
  //     },
  //   });
  // });

  // // // DATA SEED for groupe categories
  // categories.forEach(async (category) => {
  //   await prisma.category.create({
  //     data: {
  //       name: category.name,
  //       nameAr: category.name_ar,
  //       facebookLink: category.facebook_link,
  //       instagramLink: category.instagram_link,
  //       tiktokLink: category.tiktok_link,
  //       webSiteLink: "https://carrefourmaroc.ma/",
  //     },
  //   });
  // });

  // stores.forEach(async (store) => {
  //   let city = await prisma.city.findFirst({
  //     where: {
  //       name: cities[store.city_id - 1].name,
  //     },
  //   });
  //   let group = await prisma.group.findFirst({
  //     where: {
  //       name: groupes[store.groupe_id - 1].name,
  //     },
  //   });
  //   let category = await prisma.category.findFirst({
  //     where: {
  //       name: categories[store.category_id - 1].name,
  //     },
  //   });

  //   console.log(cities[store.city_id - 1]);
  //   console.log(city);

  //   await prisma.store.create({
  //     data: {
  //       name: store.name_fr,
  //       latitude: store.latitude,
  //       longitude: store.longitude,
  //       streetAdress: store.street_address,
  //       city: { connect: { id: city.id } },
  //       group: { connect: { id: group.id } },
  //       category: { connect: { id: category.id } },
  //     },
  //   });
  // });

  await Promise.all(
    messageTemplates.map(async (template) => {
      await prisma.messageTemplate.create({
        data: {
          titleAr: template.textAr,
          titleFr: template.textFr,
          contentAr: template.descriptionAr,
          contentFr: template.descriptionFr,
        },
      });
    })
  );
};

dataSeeder()
  .then(async () => {
    console.log("Seed data inserted successfully");
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
  });
